version: '3.8'

services:
  masg_web:
    build:
      context: ../../masgDockerfiles/web/
      dockerfile: masgDockerfile.dockerfile
    ports:
      - "3009:3000"
    depends_on:
      - masg_db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_NAME=Jardineria
      - DB_PASSWORD=pswJardineria
      - PORT=3000
      - HOST_API=http://localhost:3009/api
      - JWT_SECRET=MIclaveSecreta1
    networks:
      - masg_network

  masg_db:
    build:
      context: ../../masgDockerfiles/sgbd/
      dockerfile: masgDockerfile.dockerfile
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pswJardineria
      POSTGRES_DB: masgJardineria
    networks:
      - masg_network

networks:
  masg_network:
    ipam:
      driver: default
      config:
        - subnet: 172.230.10.0/24