version: "3.8"

services:
  masg-web:
    image: masg/api-jardineria-nestjs:latest
    ports:
      - "3009:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@masg-database:5432/jardineria
    volumes:
      - ./src:/app
    depends_on:
      - masg-database

  masg-database:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
