version: "3.8"

services:
  masg-web:
    image: postgres
    ports:
      - "3009:3000"
    env_file:
      - ./masgenvironment.yml
    environment:
      DATABASE_URL: postgres://postgres:password@masg-database:5432/jardineria
    volumes:
      - ./src:/app
    depends_on:
      - masg-database
    build: 
      context: ${CONTEXTO}
      dockerfile: ./masgdockerfiles/base/masgDockerfile.dockerfile
      args:
      - MASGCONTEXTO1=${CONTEXTO}
      - MASGTZ1=${TZ}
      - MASGIDRSA1=${IDRSA}
      - MASGAPP1=${APP}
      - MASGREPO1=${REPO}
    networks: 
      netomk:
          ipv4_address: 172.230.10.2
    restart: always

  masg-database:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks: 
      netomk:
          ipv4_address: 172.230.10.3
    restart: always

networks: 
  netomk:
      ipam: 
          driver: default
          config: 
              - subnet: 172.230.10.0/24 